### ISSUE TITLE
No module named 'termcolor'

### ISSUE THREAD

**Issue by Aju100** [askbuddie/ABMails#6]
program is not running, i created virtual environment and followed instructions which through documentation. After all installation, i was unable to run python file. Any ideas on how to run ?
![ab](https://user-images.githubusercontent.com/29862610/60406596-63222700-9bd6-11e9-9664-359de4fb3869.png)

**Comment by hemantapokharel** [comment]
You are getting the error because the module 'termcolor' is not properly installed in your system. I have now added 'termcolor' in requirements.txt. 

You can now update ABmails and follow the documentation properly to run the program.
OR,
simply, install termcolor with the command: pip3 install termcolor

Thanks

**Comment by Aju100** [comment]
thanks @Hemant-H9  it works.
