### ISSUE TITLE
ISSUE in FireFox version

### ISSUE THREAD

**Issue by Muna-Kopila** [askbuddie/ABMails#7]
Chrome version of ABMails is working properly. But the firefox version has some issue. I didnot receive any mails on the firefox version except from '@mailsac' domain.

**Comment by hemantapokharel** [comment]
@Muna-Kopila Thanks for letting us know. The issue in firefox version is due to the recent update in temp-mail.org , Chrome version is working because we had already updated it. We will soon update the firefox version as soon as possible. 

Thanks, 

[Edited]
@Muna-Kopila firefox version is updated now.
